### ISSUE TITLE
Docker Machine will possibly be deprecated in the future

### ISSUE THREAD

**Issue by inductor** [HPE-Japan-Presales/docker-machine-ov#12]
Ref. https://github.com/docker/roadmap/issues/245

It would be also important to see what Rancher folks will do about this.

**Comment by fideltak** [comment]
Basically Rancher node plugin is not handling Docker installtion, but handling on the Rancher side.
All this plugin is doing is setup before installing container engine such as Hardware setup and OS installtion.
We are not sure that Rancher node plugin sepecifications will be changed in the future.
Therefore the announcement you described have no impact on this project for now I believe.
However we may decide not to test for docker-machine in this project someday.
